### ISSUE TITLE
How does this library differ from Humanizer?

### ISSUE THREAD

**Issue by x2764tech** [rudyhuyn/PluralNet#1]
I already use [Humanizer](https://github.com/Humanizr/Humanizer) - what are the advantages of PluralNet?

**Comment by jnm2** [comment]
This is going to be everyone's first question. A chart would be nice.

**Comment by rudyhuyn** [comment]
The purpose of these 2 libraries are very different.

Humanizer is a library to do operations on strings, one of the operation is to pluralize a word : "man".Pluralize().

To cut a long story short, Humanizer does:
- verify if the word is "man" "woman" "child", etc...  and use the correct plural
- verify the ending of the word: potato => potatoES
- verify if the word is uncountable
- else add a S

It only supports english, no sentences and is not related numbers.

PluralNet is totally different, it's a tool for localizations (select the correct resource depends of the number), if you want to display: 
- you have removed XX item(s), you can restore this file(s) using this link.

You can create 2 resources:
- you have removed 1 item, you can restore this file using this link.
- you have removed {0} items, you can restore these files, using this link.

PluralNet will select the correct string depends of the number and will support all languages.

For example 
- 0 is singular in french
- 9999.999991 is singular for some languages cause ending with a 1
- Polish has 4 different plural forms 

etc...

I wrote an article about that, read it here:
http://www.rudyhuyn.com/blog/2016/09/28/pluralization-the-missing-part-of-net/

To conclude, both libraries are useful but has 2 different purposes, you can use both on your application
