### ISSUE TITLE
SlavicProvider never returns PluralTypeEnum.ZERO

### ISSUE THREAD

**Issue by SonicGD** [rudyhuyn/PluralNet#6]
Hello.

If `n==0` - `SlavicProvider` returns `PluralTypeEnum.MANY` but should return `PluralTypeEnum.ZERO`

**Comment by Physikbuddha** [comment]
I disagree, the `SlavicProvider` is working as intended.
See the [language plural rules at unicode.org](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ru).

**Comment by SonicGD** [comment]
Yes, you right. This is just not what i was expected. Thanks for the link.
